server:
  port: 8083
spring:
  application:
    name: lubase.cache.module
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Rx8r5NRdYWq12ylxVp2eNY9hGtf1UwSnRuCwyGNuhJdPViVLlYhEoFbYurZiIo09)
    password: ENC(aS/wGiL8T+TNg02Q80Iwy8VoU8xTPSH0oeF36f0ShbXzDZ0NEpXOkGqSVdqztJLg)
    url: ENC(PXFvgvLCHCNMfep6DuDGFzMXzurAJx+W2SZ9QnURsb6OHn5/3XlLFjAwQF0AlEz10AdeGbLPPQ0V/l7Brs0FX8MwN4/ov7nRkUI+PYv57DqNLVqu/eFn4/qGGmRidYRt0xZ4ojeQiS+fwSYBVM224V59e5mzVrENgsgNcAiemxHnXTK61paI0kMW2uSg3At+gI0woeLvi/GPKOTHLag0ssxFH4BjJn2FfcLcEWp8tD4=)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  cache:
    type: redis
  redis:
    host: ENC(tPvaGrZcku8FYNCJWVEZCGcTOiufmM/vqBgfjgBzOlh7enl3nufMpZl9gtOi5zEs)
    port: 5676
    password: ENC(hEo3CvO9OKzK0tKcitwarHDoUc0asUZs0R2LFOmYn+oF/14mrXe6bkz6Jm21wa9i)
    timeout: 5000
    database: 10
#下面这些内容是为了让MyBatis映射
mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mapper/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.lubase.orm.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
